services:
  - type: web
    name: tg-media-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
      - key: TELEGRAM_CHANNEL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
